const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),crypto=require('node:crypto'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const {financeSummary}=require('../.operational-tests/lib/financeiro/calculos');
const {financeReportCsv}=require('../.operational-tests/lib/financeiro/relatorios');
const {reconcileExpenses}=require('../.operational-tests/lib/mercado-pago/expense-reconciliation');
const root=path.resolve(__dirname,'..');
function compile(source,requireTool=require,env={}){const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020}}).outputText;const m={exports:{}};new Function('module','exports','require',...Object.keys(env),js)(m,m.exports,requireTool,...Object.values(env));return m.exports;}
const styles=new Proxy({},{get:(_,name)=>name});
const {FinanceSummaryView}=compile(fs.readFileSync(path.join(root,'components/financeiro/FinanceSummaryView.tsx'),'utf8'),name=>name.endsWith('.css')?{default:styles}:require(name));
const initial=()=>({version:1,currentCompetence:'2026-10',settings:{},dsPercent:.48,rankingByCompetence:{'2026-10':123},eventsByCompetence:{'2026-10':87.65},dsKids:[],dsReceipts:{},competences:{'2026-09':{status:'CLOSED'},'2026-10':{status:'OPEN'}},personalInvoices:[],expenses:[{id:'sep',name:'CVC',kind:'CARD',competence:'2026-09',expectedAmount:10000,dueDay:30,payments:[{id:'prior',amount:4580.29,date:'2026-09-30'}]},{id:'oct',name:'Outubro',kind:'VARIABLE',competence:'2026-10',expectedAmount:2000,dueDay:10,payments:[]}],extraExpenses:[{id:'extra',competence:'2026-10',date:'2026-10-01',amount:453.69,category:'Outros',description:'Extra simulado'}],categories:[],history:[]});
const movement=amount=>({fingerprint:'simulated-three',fingerprintAliases:['simulated-three'],dateKey:'2026-10-01',amount,kind:'OUT'});
const apply=(d,splits)=>{const r=reconcileExpenses(d,movement(splits.reduce((n,x)=>n+x.amount,0)),splits,undefined,'test-three');assert.equal(r.ok,true);return r.data;};
let count=0;const test=async(name,fn)=>{await fn();console.log('OK FINANCEIRO '+(++count)+' '+name);};
const apiSource=fs.readFileSync(path.join(root,'app/api/finance/pin/route.ts'),'utf8');
function apiHarness(){
 let authorized=true,valid=true,rows=new Map(),backup,failInsert=false;
 const query=async(sql,args=[])=>{
  if(sql==='BEGIN'){backup=structuredClone(rows);return {rows:[]};}if(sql==='ROLLBACK'){rows=backup;return {rows:[]};}if(sql==='COMMIT')return {rows:[]};
  if(sql.startsWith('DELETE')){rows.delete(args[0]);return {rows:[]};}
  if(sql.startsWith('INSERT')){if(failInsert&&args[0].startsWith('finance_trust_'))throw Error('simulated database error');if(!rows.has(args[0]))rows.set(args[0],JSON.parse(args[1]));return {rows:[]};}
  if(sql.startsWith('UPDATE')){if(rows.has(args[0]))rows.set(args[0],JSON.parse(args[1]));return {rows:[]};}
  return {rows:rows.has(args[0])?[{payload:structuredClone(rows.get(args[0]))}]:[]};
 };
 // Isolated tests substitute only the credential digest, never read/store the real PIN.
 const pinHash=apiSource.match(/PIN_HASH="([a-f0-9]+)"/)[1];
 const api=compile(apiSource,name=>name==='@/lib/auth'?{isAuthorized:async()=>authorized}:name==='@/lib/db'?{pool:{query,connect:async()=>({query,release(){}})}}:name==='next/server'?{NextResponse:{json:(body,options={})=>({body,status:options.status||200,headers:options.headers,cookies:{values:[],set(...args){this.values.push(args);}}})}}:name==='node:crypto'?{...crypto,createHash:algo=>{let v;return {update(x){v=x;return this;},digest(format){if(/^\d{4}$/.test(v))return Buffer.from(valid?pinHash:'0'.repeat(64),'hex');return crypto.createHash(algo).update(v).digest(format);}};}}:require(name));
 const request=(body={},token,origin='https://dmp.test',session='session-a')=>({json:async()=>body,cookies:{get:n=>n==='dmp_session'?{value:session}:token?{value:token}:undefined},headers:{get:n=>n==='x-dmp-finance-csrf'?crypto.createHash('sha256').update('dmp_finance_csrf_v1:'+session).digest('hex'):n==='sec-fetch-site'?(origin==='https://dmp.test'?'same-origin':'cross-site'):n==='origin'?origin:null},nextUrl:{origin:'https://dmp.test'}});
 return {api,request,rows:()=>rows,authorized:v=>authorized=v,valid:v=>valid=v,fail:v=>failInsert=v};
}
module.exports=(async()=>{
 await test('quitação atual é contada no planejamento e no caixa',()=>{const d=apply(initial(),[{targetId:'oct',amount:100}]),s=financeSummary(d,'2026-10');assert.equal(s.plannedExpensesPaid,100);assert.equal(s.expensesPaid,100);assert.equal(s.payable,1900);});
 await test('PIX 5419,71 em outubro quita setembro fechado sem inflar card de outubro',()=>{const d=apply(initial(),[{targetId:'sep',amount:5419.71}]),s=financeSummary(d,'2026-10'),old=financeSummary(d,'2026-09');assert.equal(s.plannedExpensesPaid,0);assert.equal(s.expensesPaid,5419.71);assert.equal(s.totalExpensesPaid,5419.71);assert.equal(old.plannedExpensesPaid,10000);assert.equal(old.expensesPaid,4580.29);assert.equal(old.payable,0);assert.equal(d.competences['2026-09'].status,'CLOSED');});
 await test('pagamento parcial da obrigação antiga afeta apenas seu planejamento',()=>{const d=apply(initial(),[{targetId:'sep',amount:300}]);assert.equal(financeSummary(d,'2026-09').plannedExpensesPaid,4880.29);assert.equal(financeSummary(d,'2026-10').plannedExpensesPaid,0);assert.equal(financeSummary(d,'2026-10').expensesPaid,300);});
 await test('PIX misto separa obrigações de setembro/outubro e preserva caixa integral',()=>{const d=apply(initial(),[{targetId:'sep',amount:5419.71},{targetId:'oct',amount:1080.29}]),s=financeSummary(d,'2026-10');assert.equal(s.plannedExpensesPaid,1080.29);assert.equal(s.totalExpensesPaid,6500);assert.equal(s.payable,919.71);});
 await test('pagamento posterior de obrigação de outubro continua quitando outubro',()=>{const d=initial();d.expenses[1].payments.push({id:'nov',amount:501.03,date:'2026-11-01'});const s=financeSummary(d,'2026-10');assert.equal(s.plannedExpensesPaid,501.03);assert.equal(s.expensesPaid,0);assert.equal(s.payable,1498.97);});
 await test('extras não entram duas vezes em pagas ou a pagar',()=>{const s=financeSummary(initial(),'2026-10');assert.equal(s.extrasTotal,453.69);assert.equal(s.plannedExpensesPaid,0);assert.equal(s.totalExpensesPaid,0);assert.equal(s.payable,2000);});
 await test('CSV de caixa é idêntico à base antes da nova apuração',()=>{const d=apply(initial(),[{targetId:'sep',amount:5419.71},{targetId:'oct',amount:100}]);const original=require('node:child_process').execFileSync('git',['show','HEAD:lib/financeiro/calculos.ts'],{cwd:root,encoding:'utf8'});const calc=compile(original);const reports=compile(fs.readFileSync(path.join(root,'lib/financeiro/relatorios.ts'),'utf8'),n=>n==='./calculos'?calc:require(n));assert.equal(financeReportCsv(d,'2026-10'),reports.financeReportCsv(d,'2026-10'));assert.equal(financeSummary(d,'2026-10').realizedResult,calc.financeSummary(d,'2026-10').realizedResult);});
 await test('recarga repete leitura sem mutação ou duplicidade',()=>{const d=apply(initial(),[{targetId:'sep',amount:5419.71}]),before=JSON.stringify(d);assert.deepEqual(financeSummary(d,'2026-10'),financeSummary(structuredClone(d),'2026-10'));assert.equal(JSON.stringify(d),before);});
 await test('diferença de centavos é preservada sem ajuste aproximado',()=>{const d=initial();d.expenses[1].expectedAmount=21276.33;d.expenses[1].payments.push({id:'oct-pay',amount:4376,date:'2026-10-01'});const s=financeSummary(apply(d,[{targetId:'sep',amount:5419.71}]),'2026-10');assert.equal(s.plannedExpensesPaid,4376);assert.equal(s.expensesPaid,9795.71);assert.equal(s.payable,16900.33);});
 await test('cinco posições DS incluem Eventos real e zero',()=>{for(const value of [87.65,0]){const d=initial();d.eventsByCompetence['2026-10']=value;const html=renderToStaticMarkup(React.createElement(FinanceSummaryView,{summary:financeSummary(d),mercadoPagoBalance:null,onOpen(){},onFilter(){}}));assert.match(html,/summaryFive/);assert.match(html,/Eventos/);assert.ok(html.includes(new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)));}});
 await test('pagas geral e inferior compartilham a mesma definição e preservam extras',()=>{const d=apply(initial(),[{targetId:'sep',amount:5419.71},{targetId:'oct',amount:100}]);const html=renderToStaticMarkup(React.createElement(FinanceSummaryView,{summary:financeSummary(d),mercadoPagoBalance:12,onOpen(){},onFilter(){}}));assert.equal(html.split('R$ 100,00').length-1,2);assert.equal(html.split('Gastos extras do mês').length-1,2);assert.ok(!html.includes('5.519,71'));const page=fs.readFileSync(path.join(root,'components/financeiro/FinanceiroPage.tsx'),'utf8');assert.ok(!page.includes('<h2>Vencimentos da semana</h2>'));assert.ok(page.includes('<h2>Movimentações recentes</h2>'));});
 await test('layout não inclui valores ilustrativos nem setas informativas inertes',()=>{const html=renderToStaticMarkup(React.createElement(FinanceSummaryView,{summary:financeSummary(initial()),mercadoPagoBalance:12,onOpen(){},onFilter(){}}));assert.ok(!html.includes('31.149,56'));assert.match(html,/Saldo projetado/);const tops=html.slice(html.indexOf('summaryBalances'),html.indexOf('summaryOverview'));assert.ok(!tops.includes('<button'));});
 await test('links reais preservam destinos e filtros sem controle inerte',()=>{
 const calls=[];const jsx=(type,props)=>typeof type==='function'?type(props):({type,props});
 const View=compile(fs.readFileSync(path.join(root,'components/financeiro/FinanceSummaryView.tsx'),'utf8'),n=>n.endsWith('.css')?{default:styles}:n==='react/jsx-runtime'?{jsx,jsxs:jsx}:require(n)).FinanceSummaryView;
 const tree=View({summary:financeSummary(initial()),mercadoPagoBalance:null,onOpen:t=>calls.push(t),onFilter:(f,t)=>calls.push(t+':'+f)}),buttons=[];
 function visit(n){if(!n)return;if(Array.isArray(n)){n.forEach(visit);return;}if(n.type==='button')buttons.push(n);visit(n.props?.children);}
 visit(tree);assert.equal(buttons.length,10);buttons.forEach(b=>{assert.equal(typeof b.props.onClick,'function');b.props.onClick();});
 assert.deepEqual(calls,['personal:ALL','personal:PAID','personal:OPEN','expenses:ALL','expenses:PAID','expenses:OPEN','extras','personal','ds','expenses']);
 });
 await test('cookie de confiança usa Secure em produção',async()=>{const previous=process.env.NODE_ENV;process.env.NODE_ENV='production';try{const h=apiHarness(),r=await h.api.POST(h.request({pin:'0000',trustDevice:true}));assert.equal(r.cookies.values[0][2].secure,true);}finally{if(previous===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=previous;}});
 await test('consentimento do modal acompanha PIN automático e é limpo após registrar',async()=>{
  const app=fs.readFileSync(path.join(root,'components/DmpApp.tsx'),'utf8'),start=app.indexOf('  async function unlockFinance('),end=app.indexOf('  if(!navigationReady)',start);let body,trust=true,view='today';
  const api=compile(app.slice(start,end)+'exports.unlock=unlockFinance;',require,{financePin:'0000',financeSubmitting:{current:false},financeAttempt:{current:0},setFinanceBusy(){},setFinancePin(){},setFinancePinError(){},setFinanceTrust:v=>trust=v,setShowFinancePin(){},setView:v=>view=v,FINANCE_UNLOCK_KEY:'test',sessionStorage:{setItem(){}},fetch:async(url,opts)=>{if(!opts?.method)return {ok:true,json:async()=>({csrfToken:'test-csrf'})};body=JSON.parse(opts.body);return {ok:true,json:async()=>({until:123})};}});
  await api.unlock(undefined,'0000',true);assert.equal(body.trustDevice,true);assert.equal(trust,false);assert.equal(view,'finance');
 });
 const h=apiHarness();
 await test('dispositivo desconhecido ou UA simulado não recebe isenção',async()=>{const r=await h.api.GET(h.request());assert.equal(r.body.unlocked,false);assert.equal(r.body.trusted,false);});
 await test('registro de confiança exige PIN completo e válido',async()=>{assert.equal((await h.api.POST(h.request({pin:'1',trustDevice:true}))).status,400);h.valid(false);const r=await h.api.POST(h.request({pin:'0000',trustDevice:true}));assert.equal(r.status,403);assert.equal(r.cookies.values.length,0);assert.ok(![...h.rows().keys()].some(k=>k.startsWith('finance_trust_')));h.valid(true);});
 let token;
 await test('consentimento após PIN gera segredo aleatório e cookie HttpOnly',async()=>{const r=await h.api.POST(h.request({pin:'0000',trustDevice:true}));assert.equal(r.status,200);const [name,value,opts]=r.cookies.values[0];token=value;assert.equal(name,'dmp_finance_trust');assert.match(value,/^[a-f0-9]{64}$/);assert.equal(opts.httpOnly,true);assert.equal(opts.sameSite,'strict');assert.equal(opts.maxAge,2592000);assert.ok(!JSON.stringify([...h.rows()]).includes(token));});
 await test('celular registrado abre sem repetir PIN mas ainda exige login',async()=>{const r=await h.api.GET(h.request({},token));assert.equal(r.body.trusted,true);assert.equal(r.body.unlocked,true);assert.ok(r.body.until<=Date.now()+600000);h.authorized(false);assert.equal((await h.api.GET(h.request({},token))).status,401);h.authorized(true);});
 await test('cookie inexistente ou forjado não concede confiança',async()=>{const r=await h.api.GET(h.request({},'f'.repeat(64),'https://dmp.test','another-session'));assert.equal(r.body.trusted,false);assert.equal(r.body.unlocked,false);});
 await test('desktop sem confiança mantém os dez minutos de PIN',async()=>{const r=await h.api.POST(h.request({pin:'0000'},undefined,'https://dmp.test','desktop'));assert.equal(r.cookies.values.length,0);assert.equal(r.body.trusted,false);assert.ok(r.body.until>Date.now()+599000);assert.equal((await h.api.GET(h.request({},undefined,'https://dmp.test','desktop'))).body.unlocked,true);});
 await test('confiança expirada pede PIN após prazo normal expirar',async()=>{for(const [k,v]of h.rows())h.rows().set(k,{...v,until:Date.now()-1});const r=await h.api.GET(h.request({},token));assert.equal(r.body.trusted,false);assert.equal(r.body.unlocked,false);});
 await test('revogação apaga confiança e liberação temporária',async()=>{const created=await h.api.POST(h.request({pin:'0000',trustDevice:true}));token=created.cookies.values[0][1];const revoked=await h.api.DELETE(h.request({},token));assert.equal(revoked.status,200);assert.equal(revoked.cookies.values[0][2].maxAge,0);const r=await h.api.GET(h.request({},token));assert.equal(r.body.trusted,false);assert.equal(r.body.unlocked,false);});
 await test('origem externa não cadastra nem revoga confiança',async()=>{assert.equal((await h.api.POST(h.request({pin:'0000',trustDevice:true},undefined,'https://evil.test'))).status,403);assert.equal((await h.api.DELETE(h.request({},undefined,'https://evil.test'))).status,403);});
 await test('revogar não apaga limites de tentativa de PIN',async()=>{h.valid(false);for(let i=0;i<5;i++)await h.api.POST(h.request({pin:'0000'}));assert.equal((await h.api.POST(h.request({pin:'0000'}))).status,429);await h.api.DELETE(h.request());assert.equal((await h.api.POST(h.request({pin:'0000'}))).status,429);h.valid(true);for(const [k,v]of h.rows())h.rows().set(k,{...v,blockedUntil:0,attempts:0});});
 await test('erro no registro reverte desbloqueio e não emite cookie',async()=>{h.fail(true);const before=JSON.stringify([...h.rows()]);const r=await h.api.POST(h.request({pin:'0000',trustDevice:true}));assert.equal(r.status,500);assert.equal(r.cookies.values.length,0);assert.equal(JSON.stringify([...h.rows()]),before);});
 console.log(count+' testes das três atualizações financeiras passaram.');
})();
