const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),postcss=require('postcss');
const root=path.resolve(__dirname,'..'),baseline=require('./home-final-baseline.json'),css=fs.readFileSync(path.join(root,'components/HomeCentral.module.css'),'utf8'),sheet=postcss.parse(css);
function declarations(selector,width){const values={};sheet.walkRules(rule=>{if(!rule.selector.split(',').map(s=>s.trim()).includes(selector))return;for(let p=rule.parent;p;p=p.parent)if(p.type==='atrule'&&p.name==='media'){const min=p.params.match(/min-width:\s*(\d+)px/),max=p.params.match(/max-width:\s*(\d+)px/);if(min&&width<+min[1]||max&&width>+max[1])return;}rule.walkDecls(d=>values[d.prop]=d.value);});return values;}
let n=0;function test(name,f){f();console.log('OK HOME FINAL '+(++n)+' '+name);}
module.exports=(async()=>{
test('todos os demais arquivos de produção idênticos à base oficial ba641c8',()=>{for(const [file,hash]of Object.entries(baseline.hashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file)).toString('binary').replace(/\r\n/g,'\n'),'binary').digest('hex'),hash,file);});
test('CSS antigo e Agenda intocados; acréscimo restrito a media queries',()=>{assert.ok(css.startsWith(baseline.css));const delta=css.slice(baseline.css.length),ast=postcss.parse(delta);assert.ok(!/calendar-today|data-home-size-key|commitments|todoist-widget|finance|spotify/.test(delta));for(const node of ast.nodes)if(node.type!=='comment')assert.equal(node.type,'atrule');});
const grid='.central :global(.today-highlight-grid.todoist-home-grid)';
for(const width of [1280,1440,1600,1920])test('desktop '+width+': compactação, calendário preservado e treino ampliado',()=>{assert.equal(declarations('.central',width)['row-gap'],'12px');const calendar=declarations(grid+'>:global(.mini-month)',width);assert.equal(calendar['grid-column'],'1/span 5');assert.equal(calendar.padding,'12px');assert.equal(declarations(grid+'>:global(.performance-today-card)',width)['grid-column'],'16/span 5');for(const card of ['today-summary-card','month-closing-today-card']){const lines='.central :global(.'+card+') :global(.highlight-lines)';assert.equal(declarations(lines,width)['grid-auto-rows'],'minmax(84px,1fr)');const tile=declarations(grid+'>:global(.'+card+') :global(.highlight-lines)>small',width);assert.equal(tile['min-height'],'84px');assert.equal(tile.padding,'8px 6px 20px');assert.equal(declarations(grid+'>:global(.'+card+')',width).height,'auto');}});
for(const width of [320,390])test('mobile '+width+': 3x2 sem largura residual e Resumo aprovado preservado',()=>{const lines='.central :global(.month-closing-today-card) :global(.highlight-lines)';assert.equal(declarations(lines,width)['grid-template-columns'],'repeat(3,minmax(0,1fr))');assert.equal(declarations(lines,width).width,'100%');assert.equal(declarations(lines,width).gap,'8px');assert.equal(declarations('.central :global(.today-summary-card) :global(.highlight-lines)',width)['grid-template-columns'],'repeat(2,minmax(0,1fr))');const tile=declarations(lines+'>small',width);assert.equal(tile.height,'auto');assert.equal(tile['min-width'],'0');assert.equal(tile.overflow,'visible');assert.equal(declarations(lines+'>small>b:first-child',width).margin,'0 0 5px');assert.equal(declarations('.central',width)['row-gap'],undefined);});
console.log('Home final: '+n+' testes passaram. Validação estrutural, sem screenshots.');
})();
