const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),styles=new Proxy({},{get:(_,key)=>key});
const FixedDate=class extends Date{constructor(...args){super(...(args.length?args:['2026-10-03T12:00:00Z']));}static now(){return new Date('2026-10-03T12:00:00Z').getTime();}};
let state=[],cursor=0,override={};const hooks={...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=i in override?override[i]:typeof initial==='function'?initial():initial;return[state[i],next=>{state[i]=typeof next==='function'?next(state[i]):next;}];},useEffect(){},useMemo(fn){return fn();}};
const cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);let code=fs.readFileSync(file,'utf8');if(file.endsWith('KidsReplacementBalance.tsx'))code+='\nexport {computeKidsReplacementOperationMetrics};';const m={exports:{}};cache.set(file,m.exports);const requireLocal=name=>{if(name==='react')return hooks;if(name.endsWith('.css'))return{__esModule:true,default:styles};if(name.startsWith('@/')||name.startsWith('.')){let base=name.startsWith('@/')?path.join(root,name.slice(2)):path.resolve(path.dirname(file),name);let target=['.ts','.tsx','.cjs',''].map(ext=>base+ext).find(f=>fs.existsSync(f)&&fs.statSync(f).isFile());if(target)return load(target);}return require(name);};const js=ts.transpileModule(code,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;new Function('module','exports','require','Date',js)(m,m.exports,requireLocal,FixedDate);cache.set(file,m.exports);return m.exports;}
const kidsUI=load(path.join(root,'components/kids/KidsReplacementBalance.tsx'));
const balance=load(path.join(root,'lib/kids/replacement-balance.ts'));
const insight=load(path.join(root,'lib/assessments/insights.ts'));
const Insights=load(path.join(root,'components/assessments/AssessmentInsights.tsx')).default;
const evolution=load(path.join(root,'lib/performance-evolution.ts'));
const Evolution=load(path.join(root,'components/performance/PerformanceEvolution.tsx')).default;
function render(fn,props,initial={}){state=[];override=initial;cursor=0;return fn(props);}
function rerender(fn,props){cursor=0;return fn(props);}
function nodes(node,predicate,out=[]){if(!node)return out;if(Array.isArray(node)){node.forEach(n=>nodes(n,predicate,out));return out;}if(typeof node==='object'&&node.props){if(predicate(node))out.push(node);nodes(node.props.children,predicate,out);}return out;}
const text=n=>renderToStaticMarkup(n);
const data=()=>({version:1,semesterStart:'2026-08-01',semesterEnd:'2026-12-31',classes:[{id:'c',name:'Turma teste segunda 16h',startTime:'16:00',endTime:'17:00',active:true,students:[{id:'s',name:'Aluno teste',active:true},{id:'zero',name:'Aluno zero',active:true},{id:'old',name:'Aluno inativo',active:false}]}],lessons:[],replacements:[],replacementUsages:[]});
const lesson=(id,date,patch={})=>({id,classId:'c',date,status:'COMPLETED',attendance:{s:'PRESENT'},...patch});
const metric=(d,period='semester',all=false)=>kidsUI.computeKidsReplacementOperationMetrics(d,period,all);
let count=0;function test(name,fn){fn();console.log('OK MESTRE '+(++count)+' '+name);}
const row=d=>metric(d).rows.find(r=>r.id==='s');
const before=d=>JSON.stringify(d);
const kidsProps=d=>({data:d});
const general=d=>{const p=kidsProps(d);let tree=render(kidsUI.KidsReplacementOperationSummary,p);nodes(tree,n=>n.type==='button'&&text(n).includes('Controle de reposições por aluno'))[0].props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);nodes(tree,n=>n.type==='button'&&n.props['aria-controls']==='replacement-history-s')[0].props.onClick();return rerender(kidsUI.KidsReplacementOperationSummary,p);};
const cancelled=()=>{const d=data();d.lessons=[lesson('cancel','2026-09-01',{status:'CANCELLED',replacementEligible:true}),lesson('r','2026-09-02',{kind:'REPLACEMENT',replacementStudentIds:['s'],attendance:{s:'ABSENT'}})];return d;};
test('controle geral inclui zero e exclui inativo; cadastro e dados históricos preservados',()=>{const d=data();assert.equal(metric(d).rows.length,2);assert.equal(metric(d,'semester',true).rows.length,3);const html=text(general(d));assert.match(html,/Aluno zero/);assert.doesNotMatch(html,/Aluno inativo/);});
test('saldo a repor é o inverso declarado do saldo oficial',()=>{const d=cancelled();d.lessons.push(lesson('extra','2026-09-03',{kind:'REPLACEMENT',replacementStudentIds:['s']}));assert.equal(row(d).netBalance,(-balance.computeKidsStudentReplacementBalance(d,'s').balance||0));assert.equal(row(d).netBalance,-1);});
test('saldo negativo revela reposição extra concreta e amarela',()=>{const d=cancelled();d.lessons.push(lesson('extra','2026-09-03',{kind:'REPLACEMENT',replacementStudentIds:['s']}));const html=text(general(d));assert.match(html,/Reposições antecipadas ainda sem cancelamento vinculado/);assert.match(html,/03\/09\/2026/);assert.match(html,/detailAnticipated/);});
test('cancelamento pendente fica vermelho e verde permanece compensado',()=>{const d=cancelled();d.lessons.push(lesson('cancel2','2026-09-04',{status:'CANCELLED',replacementEligible:true}));const html=text(general(d));assert.match(html,/detailResolved/);assert.match(html,/detailPending/);assert.equal(row(d).netBalance,1);});
test('falta na reposição compensada é verde no geral e não altera saldo',()=>{const d=cancelled(),old=before(d);assert.match(text(general(d)),/detailResolved/);assert.equal(row(d).netBalance,0);assert.equal(before(d),old);});
test('quinta aula contabilizada fica verde e identificada por texto',()=>{const d=data();d.lessons=['01','08','15','22','29'].map((day,index)=>lesson('f'+index,'2026-09-'+day,index===0?{status:'CANCELLED',replacementEligible:true}:{}));const html=text(general(d));assert.match(html,/5ª aula do mês/);assert.match(html,/detailResolved/);assert.doesNotMatch(html,/detailAnticipated/);});
test('quinta aula futura não é falta realizada mas continua no saldo oficial',()=>{const d=data();d.lessons=['01','08','15','22','29'].map((day,index)=>lesson('f'+index,'2026-10-'+day,{status:'SCHEDULED',attendance:{s:'ABSENT'}}));assert.equal(metric(d).absentReplacements,0);assert.equal(row(d).netBalance,-1);assert.match(text(general(d)),/5ª aula agendada ainda sem cancelamento vinculado/);});
test('novo card conta somente faltas de reposições realizadas',()=>{const d=cancelled();d.lessons.push(lesson('regular','2026-09-05',{attendance:{s:'ABSENT'}}));assert.equal(metric(d).absentReplacements,1);});
test('filtro mensal exclui faltas de setembro sem apagar saldo acumulado',()=>{const d=cancelled();assert.equal(metric(d,'month').absentReplacements,0);assert.equal(metric(d,'semester').absentReplacements,1);assert.equal(metric(d,'month').rows.find(r=>r.id==='s').netBalance,row(d).netBalance);});
test('registro imutável de uso sem vínculo mantém falta e origem oficial',()=>{const d=data();d.replacementUsages=[{id:'u',studentId:'s',lessonId:'missing',date:'2026-09-02',attendance:'ABSENT'}];assert.equal(metric(d).absentReplacements,1);assert.equal(row(d).replacedEvents.length,1);});
test('falta em quinta aula concluída inclui apenas evento oficial único',()=>{const d=data();d.lessons=['01','08','15','22','29'].map((day,index)=>lesson('f'+index,'2026-09-'+day,index===4?{attendance:{s:'ABSENT'}}:{}));assert.equal(metric(d).absentReplacements,1);});
test('card substituído mantém cinco botões e abre ocorrências correspondentes',()=>{const d=cancelled(),p=kidsProps(d);let tree=render(kidsUI.KidsReplacementOperationSummary,p);const cards=nodes(tree,n=>n.type==='button'&&n.props.children?.some?.(child=>child?.type==='em'));assert.equal(cards.length,5);const button=cards.find(n=>text(n).includes('Reposições com falta'));assert.ok(button);button.props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);assert.match(text(tree),/Falta na reposição — crédito consumido/);assert.doesNotMatch(text(tree),/Já agendados/);});
test('busca por criança filtra modal sem qualquer mutação',()=>{const d=cancelled(),old=before(d),p=kidsProps(d);let tree=general(d);nodes(tree,n=>n.type==='input'&&n.props.placeholder==='Buscar criança...')[0].props.onChange({target:{value:'zero'}});tree=rerender(kidsUI.KidsReplacementOperationSummary,p);assert.match(text(tree),/Aluno zero/);assert.doesNotMatch(text(tree),/Aluno teste/);assert.equal(before(d),old);});
test('realizadas mantêm vermelho de falta e legenda de comparecimento',()=>{const d=cancelled(),p=kidsProps(d);let tree=render(kidsUI.KidsReplacementOperationSummary,p);nodes(tree,n=>n.type==='button'&&text(n).includes('Reposições feitas'))[0].props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);assert.match(text(tree),/Verde: presença na reposição/);assert.match(text(tree),/Vermelho: falta na reposição/);assert.match(text(tree),/detailAbsent/);});
test('controle mostra origem do saldo fora do filtro mensal',()=>{const d=cancelled(),p=kidsProps(d);let tree=render(kidsUI.KidsReplacementOperationSummary,p);nodes(tree,n=>n.type==='button'&&text(n).includes('Este mês'))[0].props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);nodes(tree,n=>n.type==='button'&&text(n).includes('Controle de reposições por aluno'))[0].props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);nodes(tree,n=>n.type==='button'&&n.props['aria-controls']==='replacement-history-s')[0].props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);assert.match(text(tree),/Origem do saldo fora do período/);});
const assessments=[{id:'a',date:'2026-07-01',weight:80,leanMass:58,bodyFatPercent:25,measurements:{},notes:'',photos:[]},{id:'b',date:'2026-08-01',weight:79,leanMassPercent:75,measurements:{},notes:'',photos:[]},{id:'c',date:'2026-09-01',weight:78,muscleMass:35,bodyFatPercent:23,measurements:{},notes:'',photos:[]}];
test('série usa apenas valores originais com datas sem interpolar ausências',()=>{assert.equal(insight.assessmentInsightSeries(assessments,'weight').length,3);assert.equal(insight.assessmentInsightSeries(assessments,'muscleMass').length,1);assert.equal(insight.assessmentInsightSeries(assessments,'leanMass').length,1);});
test('massa magra percentual não é usada como massa em kg',()=>{assert.equal(insight.assessmentInsightValue(assessments[1],'leanMass'),null);assert.equal(insight.assessmentInsightValue(assessments[1],'leanMassPercent'),75);});
test('comparador B menos A e campo ausente permanecem corretos',()=>{assert.equal(insight.assessmentInsightDifference(assessments[0],assessments[2],'weight'),-2);assert.equal(insight.assessmentInsightDifference(assessments[0],assessments[2],'muscleMass'),null);});
test('aviso opcional usa última avaliação e intervalo escolhido',()=>{assert.equal(insight.assessmentReminderDate(assessments,30),'2026-10-01');assert.equal(insight.assessmentReminderDate(assessments,0),null);assert.equal(insight.assessmentReminderDate([],30),null);});
test('gráfico vazio e avaliação única renderizam sem fabricar dados',()=>{for(const list of [[],assessments.slice(0,1)]){const html=text(render(Insights,{assessments:list,preferenceKey:'s',onOpenRecord(){}}));assert.match(html,/Avaliações em perspectiva/);if(!list.length)assert.match(html,/Sem valores registrados/);else assert.match(html,/80/);}});
test('escolher A e B livremente reflete exatamente datas selecionadas',()=>{const props={assessments,preferenceKey:'s',onOpenRecord(){}},tree=render(Insights,props);nodes(tree,n=>n.type==='select'&&n.props['aria-label']==='Avaliação A')[0].props.onChange({target:{value:'a'}});nodes(tree,n=>n.type==='select'&&n.props['aria-label']==='Avaliação B')[0].props.onChange({target:{value:'b'}});assert.match(text(rerender(Insights,props)),/01\/07\/2026 \(A\)/);assert.match(text(rerender(Insights,props)),/01\/08\/2026 \(B\)/);});
test('ponto do gráfico abre registro real e não modifica avaliações',()=>{let target;const old=JSON.stringify(assessments),props={assessments,preferenceKey:'s',onOpenRecord:id=>target=id},tree=render(Insights,props);nodes(tree,n=>n.type==='button'&&text(n).includes('01/07/2026'))[0].props.onClick();assert.equal(target,'a');assert.equal(JSON.stringify(assessments),old);});
const activities=[{id:'sep',date:'2026-09-02',distanceKm:10,durationMinutes:30,elevationMeters:100},{id:'oct',date:'2026-10-01',distanceKm:0,durationMinutes:40,elevationMeters:0}];
test('evolução mensal acumula todas as quatro métricas da mesma origem',()=>{const series=evolution.performanceEvolution(activities,2026,10,3);assert.deepEqual(series.map(item=>item.count),[0,1,1]);assert.equal(series[1].distance,10);assert.equal(series[2].minutes,40);assert.equal(series[2].distance,0);});
test('janela móvel cruza anos sem incluir futuro',()=>{const series=evolution.performanceEvolution([],2026,2,12);assert.equal(series[0].key,'2025-03');assert.equal(series.at(-1).key,'2026-02');});
test('períodos de três seis e doze meses têm número exato de pontos',()=>{for(const length of [3,6,12])assert.equal(evolution.performanceEvolution(activities,2026,10,length).length,length);});
test('barras abrem somente mês original e mudanças de métrica são consultas',()=>{let selected;const props={activities,year:2026,month:10,onOpenMonth:key=>selected=key},old=JSON.stringify(activities);let tree=render(Evolution,props);nodes(tree,n=>n.type==='button'&&n.props['aria-label']?.includes('out.'))[0].props.onClick();assert.equal(selected,'2026-10');nodes(tree,n=>n.type==='select')[0].props.onChange({target:{value:'minutes'}});tree=rerender(Evolution,props);assert.match(text(tree),/Tempo por mês/);assert.equal(JSON.stringify(activities),old);});
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'master-five-preservation.json'),'utf8'));
test('autenticação proxy PIN confiança Home regras financeiras e Kids preservadas byte a byte normalizado',()=>{for(const [file,hash]of Object.entries(fixture.files)){const raw=(require('./final-combined-baseline.json').original[file]||fs.readFileSync(path.join(root,file),'utf8')).replace(/\r\n/g,'\n');assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),hash,file);}});
test('topo original da Performance e calendário permanecem exatamente iguais',()=>{const source=fs.readFileSync(path.join(root,'components/performance/PerformancePage.tsx'),'utf8').replace(/\r\n/g,'\n');const hero=source.slice(source.indexOf('        <div className={styles.hero}>'),source.indexOf('        <nav className={styles.tabs}'));assert.equal(hero,fixture.hero);});
test('síntese individual não busca nem exibe dados financeiros',()=>{const source=fs.readFileSync(path.join(root,'components/assessments/StudentConsultationSummary.tsx'),'utf8');assert.doesNotMatch(source,/fetch\(|finance|monthlyAmount/);});
test('resumo financeiro mantém todos os destinos e dados da base',()=>{const source=require('./update8-baseline.json').original['components/financeiro/FinanceSummaryView.tsx'].replace(/\r\n/g,'\n');assert.equal(crypto.createHash('sha256').update(source).digest('hex'),fixture.summaryHash);});

test('PDF do controle inclui excedentes, saldo, legenda e cores corretas sem mutação',()=>{let html='';global.window={open:()=>({document:{open(){},write(value){html=value;},close(){}}})};const d=cancelled();d.lessons.push(lesson('extra','2026-09-03',{kind:'REPLACEMENT',replacementStudentIds:['s']}));const old=before(d),tree=general(d);nodes(tree,n=>n.type==='button'&&text(n).includes('>PDF<'))[0].props.onClick();assert.match(html,/Reposições antecipadas ainda sem cancelamento vinculado/);assert.match(html,/class="resolved"/);assert.doesNotMatch(html,/azul/);assert.equal(before(d),old);delete global.window;});
test('PDF de realizadas preserva legenda presença versus falta e cor vermelha',()=>{let html='';global.window={open:()=>({document:{open(){},write(value){html=value;},close(){}}})};const d=cancelled(),props=kidsProps(d);let tree=render(kidsUI.KidsReplacementOperationSummary,props);nodes(tree,n=>n.type==='button'&&text(n).includes('Reposições feitas'))[0].props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,props);nodes(tree,n=>n.type==='button'&&text(n).includes('>PDF<'))[0].props.onClick();assert.match(html,/Verde: presença/);assert.match(html,/class="absent"/);delete global.window;});
test('PNG usa registros reais e quebra textos sem modificar o banco',()=>{const labels=[];const ctx={measureText:value=>({width:value.length*10}),fillText:value=>labels.push(value),fillRect(){},beginPath(){},roundRect(){},fill(){},stroke(){},arc(){}};global.document={createElement:()=>({getContext:()=>ctx,toBlob(){}})};const d=cancelled();d.lessons.push(lesson('extra','2026-09-03',{kind:'REPLACEMENT',replacementStudentIds:['s']}));const old=before(d),tree=general(d);nodes(tree,n=>n.type==='button'&&text(n).includes('>Imagem<'))[0].props.onClick();assert.ok(labels.some(value=>value.includes('sem cancelamento vinculado')));assert.ok(labels.some(value=>value.includes('03/09/2026')));assert.equal(before(d),old);delete global.document;});
test('preferência de aviso pode ativar e desativar sem gravar avaliações',()=>{let stored;global.localStorage={setItem:(key,value)=>stored={key,value}};const props={assessments,preferenceKey:'s',onOpenRecord(){}},old=JSON.stringify(assessments);let tree=render(Insights,props);nodes(tree,n=>n.type==='select'&&n.props.children?.some?.(child=>child?.props?.value==='0'))[0].props.onChange({target:{value:'60'}});assert.equal(stored.value,'60');tree=rerender(Insights,props);assert.match(text(tree),/Intervalo de 60 dias/);nodes(tree,n=>n.type==='select'&&n.props.value===60)[0].props.onChange({target:{value:'0'}});assert.equal(stored.value,'0');assert.equal(JSON.stringify(assessments),old);delete global.localStorage;});
test('fontes diferentes produzem aviso de limitação de comparação',()=>{const a=structuredClone(assessments);a[1].sourceFileName='Método A.pdf';a[2].sourceFileName='Método B.pdf';assert.match(text(render(Insights,{assessments:a,preferenceKey:'s',onOpenRecord(){}})),/Arquivos\/fontes de origem diferentes/);});
test('comparação percentual usa pontos percentuais e preserva campos ausentes',()=>{const props={assessments,preferenceKey:'s',onOpenRecord(){}},tree=render(Insights,props);nodes(tree,n=>n.type==='select'&&n.props['aria-label']==='Avaliação A')[0].props.onChange({target:{value:'a'}});const html=text(rerender(Insights,props));assert.match(html,/-2 p.p./);assert.match(html,/Não disponível/);});
test('quatro indicadores da Performance abrem lista do mesmo mês e métrica zero não inventa atividade',()=>{const Performance=load(path.join(root,'components/performance/PerformancePage.tsx')).default;const items=activities.map(item=>({...item,type:'CYCLING',source:'MANUAL',title:item.id}));const props={};let tree=render(Performance,props,{0:{version:1,activities:items,assessments:[],goals:[],records:[]},1:false});const metrics=nodes(tree,n=>n.props?.label?.endsWith('no mês')&&typeof n.type==='function');assert.equal(metrics.length,4);assert.equal(metrics.find(n=>n.props.label==='Distância no mês').props.value,'0,0 km');metrics[0].props.onClick();tree=rerender(Performance,props);const modal=nodes(tree,n=>n.props?.eyebrow==='ORIGEM DOS INDICADORES')[0];assert.ok(modal);const rows=nodes(modal,n=>n.props?.activity);assert.equal(rows.length,1);assert.equal(rows[0].props.activity.id,'oct');});

function historyHarness(student){
 const source=fs.readFileSync(path.join(root,'components/DmpApp.tsx'),'utf8');const start=source.indexOf('function HistoryPanel('),end=source.indexOf('\nfunction ',start+10);
 const code=source.slice(start,end)+'\nmodule.exports=HistoryPanel;';const js=ts.transpileModule(code,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
 const m={exports:{}};const extra={useState:hooks.useState,today:()=> '2026-10-03',assessmentSorted:student=>[...student.assessments].sort((a,b)=>b.date.localeCompare(a.date)),normalizeName:value=>value.toLowerCase(),formatDate:value=>value,sessionSourceLabel:item=>item.source||'',consultationStyles:styles,RecordsConsultation:load(path.join(root,'components/assessments/RecordsConsultation.tsx')).default};
 new Function('module','exports','require','Date',...Object.keys(extra),js)(m,m.exports,require,FixedDate,...Object.values(extra));return m.exports;
}
test('cards do histórico exibem listas exatas incluindo ausência antes ocultada',()=>{
 const student={sessions:[{id:'present',date:'2026-10-02',workoutName:'Treino',source:'PLANNED',notes:'',completedExercises:[]},{id:'absent',date:'2026-10-01',workoutName:'Ausência',source:'ABSENCE',notes:'Falta simulada',completedExercises:[]},{id:'old',date:'2026-08-01',workoutName:'Antigo',source:'PLANNED',notes:'',completedExercises:[]}],assessments:[{...assessments[2],date:'2026-10-01'}]};
 const History=historyHarness(student),props={student};let tree=render(History,props);const cards=nodes(tree,n=>n.type==='article'&&n.props.role==='button');assert.equal(cards.length,4);cards.find(card=>card.props['aria-label'].startsWith('Ausências.')).props.onClick();tree=rerender(History,props);let detail=nodes(tree,n=>n.props?.title==='Ausências dos últimos 30 dias')[0];assert.equal(detail.props.records.length,1);assert.equal(detail.props.records[0].id,'absent');assert.equal(detail.props.records[0].notes,'Falta simulada');
});
test('card do histórico acessível por teclado preserva intervalo e campos de origem',()=>{
 const student={sessions:[{id:'p',date:'2026-10-02',workoutName:'Treino',source:'PLANNED',notes:'origem',completedExercises:[]},{id:'old',date:'2026-07-02',workoutName:'Antigo',source:'PLANNED',notes:'',completedExercises:[]}],assessments:[]};
 const History=historyHarness(student),props={student};let tree=render(History,props);const card=nodes(tree,n=>n.type==='article'&&n.props['aria-label']?.startsWith('Registros.'))[0];let prevented=false;card.props.onKeyDown({key:'Enter',preventDefault:()=>prevented=true});tree=rerender(History,props);const detail=nodes(tree,n=>n.props?.title==='Registros dos últimos 30 dias')[0];assert.equal(detail.props.records.length,1);assert.equal(detail.props.records[0].id,'p');assert.ok(prevented);
});

test('falta na quinta aula é identificada mesmo quando rótulo oficial descreve somente o tipo',()=>{const d=data();d.lessons=['01','08','15','22','29'].map((day,index)=>lesson('f'+index,'2026-09-'+day,index===0?{status:'CANCELLED',replacementEligible:true}:index===4?{attendance:{s:'ABSENT'}}:{}));assert.match(text(general(d)),/falta registrada/);const props=kidsProps(d);let tree=render(kidsUI.KidsReplacementOperationSummary,props);nodes(tree,n=>n.type==='button'&&text(n).includes('Reposições feitas'))[0].props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,props);assert.match(text(tree),/detailAbsent/);});
test('excedentes e origem fora do período aparecem em seções separadas',()=>{const d=cancelled();d.lessons.push(lesson('extra','2026-09-03',{kind:'REPLACEMENT',replacementStudentIds:['s']}));const tree=general(d);assert.ok(nodes(tree,n=>n.type==='section'&&n.props.className==='detailExtraGroup').length>=1);});

const consultationButtons=tree=>nodes(tree,n=>n.type==='button'&&n.props['aria-controls']?.startsWith('replacement-history-'));
function collapsedGeneral(d){const p=kidsProps(d);let tree=render(kidsUI.KidsReplacementOperationSummary,p);nodes(tree,n=>n.type==='button'&&text(n).includes('Controle de reposições por aluno'))[0].props.onClick();return rerender(kidsUI.KidsReplacementOperationSummary,p);}
test('correção: painel inicial mantém cinco cards e não abre listas ou históricos',()=>{const tree=render(kidsUI.KidsReplacementOperationSummary,kidsProps(cancelled()));assert.equal(nodes(tree,n=>n.type==='button'&&n.props.children?.some?.(child=>child?.type==='em')).length,5);assert.equal(nodes(tree,n=>n.props.role==='dialog').length,0);assert.equal(consultationButtons(tree).length,0);});
test('correção: todos os cinco cards abrem um único detalhamento correspondente',()=>{for(let i=0;i<5;i++){const props=kidsProps(cancelled());let tree=render(kidsUI.KidsReplacementOperationSummary,props);nodes(tree,n=>n.type==='button'&&n.props.children?.some?.(child=>child?.type==='em'))[i].props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,props);assert.equal(nodes(tree,n=>n.props.role==='dialog').length,1);}});
test('correção: controle começa recolhido inclui zero e exclui inativo',()=>{const tree=collapsedGeneral(cancelled());assert.equal(consultationButtons(tree).length,2);assert.ok(consultationButtons(tree).every(n=>n.props['aria-expanded']===false));assert.equal(nodes(tree,n=>n.type==='div'&&n.props.id?.startsWith('replacement-history-')).length,0);assert.match(text(tree),/Aluno zero/);assert.doesNotMatch(text(tree),/Aluno inativo/);});
test('correção: somente o aluno acionado revela seu histórico e saldo negativo real',()=>{const d=cancelled();d.lessons.push(lesson('extra','2026-09-03',{kind:'REPLACEMENT',replacementStudentIds:['s']}));let tree=collapsedGeneral(d);consultationButtons(tree).find(n=>n.props['aria-controls']==='replacement-history-s').props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,kidsProps(d));assert.equal(consultationButtons(tree).filter(n=>n.props['aria-expanded']).length,1);assert.match(text(tree),/saldo -1/);assert.match(text(tree),/03\/09\/2026/);assert.match(text(tree),/Reposições antecipadas ainda sem cancelamento vinculado/);});
test('correção: selecionar outro aluno recolhe o histórico anterior',()=>{const d=cancelled(),p=kidsProps(d);let tree=general(d);consultationButtons(tree).find(n=>n.props['aria-controls']==='replacement-history-zero').props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);assert.equal(consultationButtons(tree).filter(n=>n.props['aria-expanded']).length,1);assert.equal(nodes(tree,n=>n.props.id==='replacement-history-s').length,0);assert.equal(nodes(tree,n=>n.props.id==='replacement-history-zero').length,1);});
test('correção: aluno sem eventos pode abrir e recolher sua consulta',()=>{const d=data(),p=kidsProps(d);let tree=collapsedGeneral(d);consultationButtons(tree).find(n=>n.props['aria-controls']==='replacement-history-zero').props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);assert.match(text(tree),/Sem eventos no período/);consultationButtons(tree).find(n=>n.props['aria-controls']==='replacement-history-zero').props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);assert.ok(consultationButtons(tree).every(n=>!n.props['aria-expanded']));});
test('correção: busca ignora acentos e recolhe detalhes ao filtrar',()=>{const d=cancelled();d.classes[0].students[1].name='João Zero';let tree=general(d);nodes(tree,n=>n.type==='input'&&n.props.placeholder==='Buscar criança...')[0].props.onChange({target:{value:'joao'}});tree=rerender(kidsUI.KidsReplacementOperationSummary,kidsProps(d));assert.equal(consultationButtons(tree).length,1);assert.match(text(tree),/João Zero/);assert.equal(consultationButtons(tree)[0].props['aria-expanded'],false);});
test('correção: fechar por Escape e reabrir limpa busca e histórico',()=>{const d=cancelled(),p=kidsProps(d);let tree=general(d);nodes(tree,n=>n.props.role==='dialog')[0].props.onKeyDown({key:'Escape'});tree=rerender(kidsUI.KidsReplacementOperationSummary,p);assert.equal(nodes(tree,n=>n.props.role==='dialog').length,0);nodes(tree,n=>n.type==='button'&&text(n).includes('Controle de reposições por aluno'))[0].props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);assert.ok(consultationButtons(tree).every(n=>!n.props['aria-expanded']));});
test('correção: fórmulas permanecem idênticas após seleção da população ativa',()=>{const source=fs.readFileSync(path.join(root,'components/kids/KidsReplacementBalance.tsx'),'utf8').replace(/\r\n/g,'\n');const start=source.indexOf('  const studentIds=[...students.keys()]'),end=source.indexOf('\nfunction OperationProgress',start);assert.equal(crypto.createHash('sha256').update(source.slice(start,end)).digest('hex'),'8e5c136c185a1b6ce52750c061409e9fbd4eef1220182204dceeb34668d4869f');});
test('correção: exportação continua completa mesmo com todos os alunos recolhidos',()=>{let html='';global.window={open:()=>({document:{open(){},write(v){html=v;},close(){}}})};const tree=collapsedGeneral(cancelled());assert.ok(consultationButtons(tree).every(n=>!n.props['aria-expanded']));nodes(tree,n=>n.type==='button'&&text(n).includes('>PDF<'))[0].props.onClick();assert.match(html,/02\/09\/2026/);assert.match(html,/Aluno zero/);delete global.window;});
test('correção: navegação e consulta não modificam os dados',()=>{const d=cancelled(),p=kidsProps(d),old=before(d);let tree=general(d);consultationButtons(tree)[0].props.onClick();tree=rerender(kidsUI.KidsReplacementOperationSummary,p);nodes(tree,n=>n.type==='input'&&n.props.placeholder==='Buscar criança...')[0].props.onChange({target:{value:'aluno'}});rerender(kidsUI.KidsReplacementOperationSummary,p);assert.equal(before(d),old);});

console.log(count+' testes das cinco atualizações mestre e correção de Reposições passaram.');
