const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),crypto=require('node:crypto'),postcss=require('postcss');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8').replace(/\r\n/g,'\n'),baseline=require('./update8-baseline.json');
const pix=require('../.operational-tests/lib/mercado-pago/pix-payer');
function compile(code,mocks={}){const m={exports:{}};new Function('module','exports','require',ts.transpileModule(code,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(m,m.exports,n=>mocks[n]||require(n));return m.exports;}
const {compatiblePixRecords,editPixPayer}=compile(read('lib/financeiro/pix-payer-edit.ts'),{'@/lib/mercado-pago/pix-payer':pix});
const {financeSummary}=require('../.operational-tests/lib/financeiro/calculos');
const meta={isPix:true,fingerprint:'f1',sourceId:'source-1',bankTransferId:'bank-1',amount:639,date:'2026-10-05',destination:'DS'};
function fixture(kind='DS',split=false){const metadata={...meta,destination:kind};const receipt={id:'mp-ds-one',date:'2026-10-05',amount:639,sourceName:'PIX recebido — Pagador não identificado',note:'Mercado Pago · PIX/transferência recebida',mercadoPago:metadata};const payments=(id,amount)=>({id,date:'2026-10-05',amount,note:'PIX recebido — Pagador não identificado · Mercado Pago · PIX/transferência recebida',mercadoPago:metadata});const data={version:1,currentCompetence:'2026-10',dsPercent:.48,competences:{'2026-09':{status:'CLOSED'},'2026-10':{status:'OPEN'}},personalInvoices:[{id:'i1',competence:'2026-09',studentName:'Aluno diferente',expectedAmount:1000,payments:kind==='PERSONAL'?[payments('mp-payment-one',split?300:639)]:[]},{id:'i2',competence:'2026-10',studentName:'Outro aluno',expectedAmount:1000,payments:split?[payments('mp-payment-two',339)]:[]}],dsKids:[],dsReceipts:kind==='DS'?{'2026-10':[receipt]}:{},rankingByCompetence:{},expenses:[],extraExpenses:[],categories:[],history:[{id:'mp-one',occurredAt:'2026-10-05',competence:'2026-10',description:'PIX recebido — Pagador não identificado · Mercado Pago · recebimento registrado',kind:'DS_RECEIPT_ADDED',mercadoPago:metadata}]};const state={version:1,rules:{keep:'original'},tasks:{},decisions:{f1:{fingerprint:'f1',target:kind,financeEntityId:kind==='DS'?receipt.id:'i1',automatic:false,updatedAt:'unchanged',pix:metadata}}};return {data,state};}
let count=0;async function test(name,fn){await fn();console.log('OK UPDATE8 '+(++count)+' '+name);}
const strip=v=>JSON.parse(JSON.stringify(v,(key,value)=>key==='mercadoPago'||key==='pix'?undefined:value));
const sheet=postcss.parse(read('components/HomeCentral.module.css'));function declarations(selector,width){const values={};sheet.walkRules(rule=>{if(!rule.selector.split(',').map(s=>s.trim()).includes(selector))return;for(let p=rule.parent;p;p=p.parent)if(p.type==='atrule'&&p.name==='media'){const min=p.params.match(/min-width:\s*(\d+)px/),max=p.params.match(/max-width:\s*(\d+)px/);if(min&&width<+min[1]||max&&width>+max[1])return;}rule.walkDecls(d=>values[d.prop]=d.value);});return values;}
const grid='.central :global(.today-highlight-grid.todoist-home-grid)';
module.exports=(async()=>{
await test('arquivos de produção fora do escopo idênticos à base d6804e1',()=>{for(const [file,hash]of Object.entries(baseline.hashes)){assert.equal(crypto.createHash('sha256').update(/\.(png|jpg|jpeg|ico|webp|woff|woff2|pdf)$/.test(file)?fs.readFileSync(path.join(root,file)):fs.readFileSync(path.join(root,file)).toString('utf8').replace(/\r\n/g,'\n')).digest('hex'),hash,file);}});
await test('Agenda componente, chamada e CSS existente preservados',()=>{const app=read('components/DmpApp.tsx'),old=baseline.original['components/DmpApp.tsx'];const funcs=s=>{const ast=ts.createSourceFile('app.tsx',s,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);return new Map(ast.statements.filter(n=>ts.isFunctionDeclaration(n)&&n.name).map(n=>[n.name.text,n.getText(ast)]));};assert.equal(funcs(app).get('CalendarTodayPanel'),funcs(old).get('CalendarTodayPanel'));assert.equal(app.match(/<CalendarTodayPanel[^\n]+/)[0],old.match(/<CalendarTodayPanel[^\n]+/)[0]);assert.ok(read('components/HomeCentral.module.css').startsWith(baseline.original['components/HomeCentral.module.css']));const delta=read('components/HomeCentral.module.css').slice(baseline.original['components/HomeCentral.module.css'].length);assert.ok(!/calendar-today-panel|data-home-size-key="calendar"/.test(delta));});
await test('Compromissos mantém o JSX e ações; portal fica após Agenda antes de Entrada',()=>{const app=read('components/DmpApp.tsx'),old=baseline.original['components/DmpApp.tsx'];const section=s=>s.slice(s.indexOf('<section\n        className="today-highlight-card today-notes-card'),s.indexOf('</section>',s.indexOf('<section\n        className="today-highlight-card today-notes-card'))+10);assert.equal(section(app),section(old));assert.ok(app.indexOf('id="home-desktop-commitments"')>app.indexOf('<CalendarTodayPanel'));assert.ok(app.indexOf('id="home-desktop-commitments"')<app.indexOf('id="todoist-notes-panel"'));assert.match(app,/createPortal\(commitmentsCard,slot\)/);});
for(const width of [1280,1440,1600,1920])await test('desktop '+width+': quatro blocos ordenados, crescimento natural',()=>{assert.equal(declarations(grid,width)['grid-template-columns'],'repeat(20,minmax(0,1fr))');for(const [card,col]of [['mini-month','1/span 5'],['today-summary-card','6/span 5'],['month-closing-today-card','11/span 5'],['performance-today-card','16/span 5']]){const d=declarations(grid+'>:global(.'+card+')',width);assert.equal(d['grid-column'],col);assert.equal(d['grid-row'],'1');assert.equal(d.height,'auto');assert.equal(d['max-height'],'none');assert.equal(d.overflow,'visible');}});
for(const width of [320,390])await test('mobile '+width+': linhas horizontais de largura integral e altura natural',()=>{for(const card of ['today-summary-card','month-closing-today-card']){const lines='.central :global(.'+card+') :global(.highlight-lines)';assert.equal(declarations(lines,width)['grid-template-columns'],'minmax(0,1fr)');const tile=declarations(lines+'>small',width);assert.equal(tile['min-width'],'0');assert.equal(tile.height,'auto');assert.equal(tile.overflow,'visible');assert.equal(tile['min-height'],'48px');assert.equal(declarations(lines+'>small::before',width).top,'50%');assert.equal(declarations(lines+'>small::after',width).bottom,'auto');}assert.equal(declarations('.central :global(#home-desktop-commitments)',width).display,'none');});
await test('Financeiro remove somente grupo duplicado no mobile e preserva callback compacto',()=>{const summary=read('components/financeiro/FinanceSummaryView.tsx'),original=baseline.original['components/financeiro/FinanceSummaryView.tsx'];assert.equal(summary.replace('className={`${styles.summaryGroup} ${title==="Despesas"?styles.mobileDuplicateExpenses:""}`}','className={styles.summaryGroup}'),original);assert.match(read('components/financeiro/FinanceiroPage.module.css'),/@media\(max-width:900px\)\{\.mobileDuplicateExpenses\{display:none!important\}\}/);});
for(const kind of ['DS','PERSONAL','TRANSFER','IGNORE'])await test('pagador '+kind+': somente metadados mudam, saldos/competências e histórico original intactos',()=>{const {data,state}=fixture(kind);const result=editPixPayer(data,state,'f1','  João da Silva  ','','2026-10-08');assert.deepEqual(strip(result.data),strip(data));assert.deepEqual(strip(result.state),strip(state));assert.equal(result.state.decisions.f1.pix.payerName,'  João da Silva  ');assert.equal(result.state.decisions.f1.pix.payerOrigin,'manual');for(const key of ['sourceId','bankTransferId','fingerprint','date','amount','destination'])assert.equal(result.state.decisions.f1.pix[key],state.decisions.f1.pix[key]);for(const period of ['2026-09','2026-10']){const a=financeSummary(data,period),b=financeSummary(result.data,period);for(const key in a)if(typeof a[key]==='number')assert.equal(a[key],b[key],key);}});
await test('reedição e JSON recarregado preservam nome e auditoria, sem novo pagamento',()=>{let {data,state}=fixture('PERSONAL',true);let result=editPixPayer(data,state,'f1','Primeiro','','date1');result=JSON.parse(JSON.stringify(result));result=editPixPayer(result.data,result.state,'f1','Segundo','Primeiro','date2');assert.equal(result.state.decisions.f1.pix.payerEdits.length,2);for(const invoice of result.data.personalInvoices)assert.equal(invoice.payments[0].mercadoPago.payerName,'Segundo');assert.equal(result.data.personalInvoices[0].payments.length,1);assert.equal(result.data.history.length,data.history.length);assert.match(pix.pixDisplayLabel(result.data.history[0].mercadoPago,result.data.history[0].description),/^PIX recebido — Segundo · Mercado Pago/);});
await test('limpar nome mantém origem manual e fallback explícito',()=>{const {data,state}=fixture();let result=editPixPayer(data,state,'f1','Nome','','date');result=editPixPayer(result.data,result.state,'f1','','Nome','date');assert.equal(result.state.decisions.f1.pix.payerOrigin,'manual');assert.equal(pix.pixTitle(result.state.decisions.f1.pix),'PIX recebido — Pagador não identificado');});
await test('registro antigo DS com vínculo confiável pode editar sem alterar descrição original',()=>{const {data,state}=fixture();delete state.decisions.f1.pix;delete data.dsReceipts['2026-10'][0].mercadoPago;delete data.history[0].mercadoPago;data.dsReceipts['2026-10'][0].sourceName='PIX/transferência recebida';const result=editPixPayer(data,state,'f1','Legado','','date');assert.equal(result.data.dsReceipts['2026-10'][0].mercadoPago.payerName,'Legado');assert.equal(result.data.dsReceipts['2026-10'][0].sourceName,'PIX/transferência recebida');assert.deepEqual(strip(result.data),strip(data));});
await test('legado Personal exige ID gerado pelo fingerprint e vínculo único',()=>{const {data,state}=fixture('PERSONAL');delete state.decisions.f1.pix;const p=data.personalInvoices[0].payments[0];delete p.mercadoPago;p.note='Mercado Pago · PIX/transferência recebida';assert.equal(compatiblePixRecords(data,state).length,0);p.id='mp-payment-'+crypto.createHash('sha256').update('f1|PERSONAL|i1').digest('hex').slice(0,24);assert.equal(compatiblePixRecords(data,state).length,1);assert.equal(editPixPayer(data,state,'f1','Legado','','date').data.personalInvoices[0].payments[0].mercadoPago.payerName,'Legado');});
await test('incompatível, vínculo ausente, duplicado, conflito e segredo são rejeitados',()=>{const {data,state}=fixture();assert.throws(()=>editPixPayer(data,state,'missing','Nome','','date'));assert.throws(()=>editPixPayer(data,state,'f1','Nome','Outronome','date'));assert.throws(()=>editPixPayer(data,state,'f1','Bearer segredo','','date'));const bad=structuredClone(state);bad.decisions.f1.target='EXPENSE';assert.throws(()=>editPixPayer(data,bad,'f1','Nome','','date'));const dup=structuredClone(data);dup.dsReceipts['2026-10'].push(structuredClone(dup.dsReceipts['2026-10'][0]));assert.equal(compatiblePixRecords(dup,state).length,0);assert.throws(()=>editPixPayer(dup,state,'f1','Nome','','date'));});
await test('API autentica GET/PATCH, usa locks e revisão, sem chamada Mercado Pago ou cálculo',()=>{const route=read('app/api/finance/pix-payer/route.ts');assert.equal((route.match(/isAuthorized\(request\)/g)||[]).length,2);assert.match(route,/x-dmp-expected-updated-at/);assert.match(route,/FOR UPDATE/);assert.ok(route.indexOf('[STATE]')<route.indexOf('[FINANCE]'));assert.match(route,/COMMIT/);assert.match(route,/ROLLBACK/);assert.ok(!/fetch\(|api\.mercadopago|applyFinanceCommand|financeSummary/.test(route));});
await test('botões em recibos DS/Personal, lista recente e histórico; formulário acessível e reedição',()=>{const page=read('components/financeiro/FinanceiroPage.tsx'),payments=read('components/financeiro/PersonalReceipts.tsx'),editor=read('components/financeiro/PixPayerEditor.tsx');assert.match(page,/recordId=\{receipt.id\}/);assert.match(page,/recordId=\{item.id\}/);assert.match(payments,/recordId=\{payment.id\}/);assert.match(editor,/role="dialog" aria-modal="true"/);assert.match(editor,/maxLength=\{200\}/);assert.match(editor,/expectedName:selected.pix.payerName\|\|''/);assert.match(page,/currentCompetence:data.currentCompetence/);});

function endpointHarness(authorized=true,failFinance=false){
 let {data,state}=fixture();let snapshot,queries=0;const revision='2026-10-08T18:00:00.000Z';
 const query=async(sql,args=[])=>{queries++;if(sql==='BEGIN'){snapshot={data:structuredClone(data),state:structuredClone(state)};return {rows:[]};}if(sql==='ROLLBACK'){if(snapshot){data=snapshot.data;state=snapshot.state;}return {rows:[]};}if(sql==='COMMIT')return {rows:[]};if(sql.includes('ANY'))return {rows:[{id:'finance_v1',payload:data},{id:'mercado_pago_reconciliation_v1',payload:state}]};if(sql.startsWith('SELECT'))return {rows:[{payload:structuredClone(args[0]==='finance_v1'?data:state),updated_at:revision}]};if(sql.startsWith('UPDATE')){if(args[0]==='finance_v1'){if(failFinance)throw new Error('storage failed');data=JSON.parse(args[1]);}else state=JSON.parse(args[1]);}return {rows:[]};};
 const api=compile(read('app/api/finance/pix-payer/route.ts'),{'@/lib/auth':{isAuthorized:async()=>authorized},'@/lib/db':{pool:{query,connect:async()=>({query,release(){}})}},'@/lib/financeiro/pix-payer-edit':{compatiblePixRecords,editPixPayer},'next/server':{NextResponse:{json:(value,options)=>({value,status:options?.status||200})}}});
 return {api,request(name='Novo',expected='',version=revision){return {json:async()=>({fingerprint:'f1',payerName:name,expectedName:expected}),headers:{get:()=>version}};},get data(){return data;},get state(){return state;},get queries(){return queries;}};
}
await test('HTTP não autenticado bloqueia leitura e edição sem tocar no banco',async()=>{const h=endpointHarness(false);assert.equal((await h.api.GET(h.request())).status,401);assert.equal((await h.api.PATCH(h.request())).status,401);assert.equal(h.queries,0);});
await test('HTTP GET lista compatíveis; PATCH persiste e permite nova edição sem mexer nos valores',async()=>{const h=endpointHarness();assert.equal((await h.api.GET(h.request())).value.records.length,1);const old=strip(h.data);assert.equal((await h.api.PATCH(h.request('João'))).status,200);assert.equal((await h.api.PATCH(h.request('Maria','João'))).status,200);assert.deepEqual(strip(h.data),old);assert.equal(h.state.decisions.f1.pix.payerName,'Maria');assert.equal(h.state.decisions.f1.pix.payerEdits.length,2);});
await test('HTTP revisão financeira divergente impede gravação; nome concorrente também bloqueado',async()=>{const h=endpointHarness();const before=JSON.stringify(h.data);assert.equal((await h.api.PATCH(h.request('Nome','','old-version'))).status,409);assert.equal(JSON.stringify(h.data),before);assert.equal((await h.api.PATCH(h.request('Nome','nome em outra aba'))).status,400);assert.equal(JSON.stringify(h.data),before);});
await test('HTTP falha de storage reverte estado e Financeiro juntos; sem expor erro interno',async()=>{const h=endpointHarness(true,true);const before=JSON.stringify({data:h.data,state:h.state});const response=await h.api.PATCH(h.request('Nome'));assert.equal(response.status,400);assert.ok(!response.value.error.includes('storage'));assert.equal(JSON.stringify({data:h.data,state:h.state}),before);});
await test('HTTP credencial em texto rejeitada e não persistida',async()=>{const h=endpointHarness();assert.equal((await h.api.PATCH(h.request('Bearer segredo'))).status,400);assert.equal(h.state.decisions.f1.pix.payerName,undefined);assert.equal(h.data.dsReceipts['2026-10'][0].mercadoPago.payerName,undefined);});

console.log('UPDATE8: '+count+' testes passaram.');
})();
