"use client";
import type {Student,CalendarEvent,Session} from "@/types/models";
import styles from "./AssessmentInsights.module.css";
export default function StudentConsultationSummary({student,events,onOpen,onAgenda,onOpenSession}:{student:Student;events:CalendarEvent[];onOpen:(tab:"history"|"assessments"|"workouts")=>void;onAgenda:(date:string)=>void;onOpenSession:(session:Session)=>void}){
 const now=Date.now();const upcoming=events.filter(event=>Date.parse(event.end)>now).sort((a,b)=>a.start.localeCompare(b.start)).slice(0,3);
 const sessions=[...student.sessions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);
 const latest=[...student.assessments].sort((a,b)=>b.date.localeCompare(a.date))[0];
 return <section className={styles.insights} aria-label="Síntese de consultas do aluno"><header><div><small>REGISTROS DO ALUNO</small><h3>Últimos registros e próximos compromissos</h3></div></header><div className={styles.selectors}><div><b>Sessões recentes</b><div className={styles.pointLinks}>{sessions.length?sessions.map(session=><button key={session.id} type="button" onClick={()=>onOpenSession(session)}>{session.date.split("-").reverse().join("/")} · {session.workoutName}{session.source==="ABSENCE"?" · Ausência":""}</button>):<p>Nenhuma sessão registrada.</p>}</div><button type="button" onClick={()=>onOpen("workouts")}>{student.workouts.filter(workout=>workout.active).length} fichas ativas · Ver fichas</button></div><div><b>Avaliações e agenda</b><div className={styles.pointLinks}><button type="button" onClick={()=>onOpen("assessments")}>{student.assessments.length} avaliações · {latest?`Última: ${latest.date.split("-").reverse().join("/")}`:"Sem avaliação"}</button>{upcoming.map(event=><button type="button" key={event.id} onClick={()=>onAgenda(event.start.slice(0,10))}>{event.start.slice(0,10).split("-").reverse().join("/")} · {event.summary}</button>)}</div>{!upcoming.length?<p>Nenhum compromisso futuro vinculado na agenda carregada.</p>:null}</div></div></section>;
}
