"use client";
import {useState} from "react";
import type {PerformanceActivity,PerformanceGoal} from "@/types/performance";
import {performanceInsights,activityTotals,changePercent} from "@/lib/performance-insights";
import styles from "./PerformanceSummaryInsights.module.css";
const labels:Record<string,string>={CYCLING:"Ciclismo",STRENGTH:"Musculação",PILATES:"Pilates",RUNNING:"Corrida",TENNIS:"Tênis",OTHER:"Outros"};
const metrics=[['distance','Distância','km'],['minutes','Tempo','min'],['elevation','Altimetria','m'],['count','Treinos','']] as const;
const fmt=(n:number)=>n.toLocaleString("pt-BR",{maximumFractionDigits:1});
const date=(d:string)=>d?d.split('-').reverse().join('/'):'Sem registros';
function Origin({items,onOpen}:{items:PerformanceActivity[];onOpen:(a:PerformanceActivity)=>void}){return <details className={styles.origin}><summary>Ver {items.length} registros de origem</summary>{items.length?items.map(a=><button key={a.id} type="button" onClick={()=>onOpen(a)}><span>{a.title||labels[a.type]}<small>{date(a.date)} · {labels[a.type]}</small></span><span>→</span></button>):<p>Nenhuma atividade registrada nesse intervalo.</p>}</details>;}
function Totals({items,previous}:{items:PerformanceActivity[];previous?:PerformanceActivity[]}){const totals=activityTotals(items),old=previous?activityTotals(previous):null;return <div className={styles.totals}>{metrics.map(([key,label,unit])=>{const percent=old?changePercent(totals[key],old[key]):null;return <div key={key}><small>{label}</small><strong>{fmt(totals[key])} {unit}</strong>{old?<span>{percent===null?"Sem base percentual":`${percent>0?'+':''}${fmt(percent)}%`} · anterior {fmt(old[key])} {unit}</span>:null}</div>;})}</div>;}
export function PerformanceStreak({activities,today,onOpen}:{activities:PerformanceActivity[];today:string;onOpen:(a:PerformanceActivity)=>void}){const {streak,items}=performanceInsights(activities,today);return <section className={styles.panel}><header><div><small>CONSISTÊNCIA DOS REGISTROS</small><h2>Sequência de atividades</h2></div></header><div className={styles.totals}><div><small>Sequência atual</small><strong>{streak.current} dias</strong><span>Termina hoje ou ontem</span></div><div><small>Maior sequência registrada</small><strong>{streak.longest} dias</strong><span>{streak.start?`${date(streak.start)} a ${date(streak.end)}`:'Sem registros'}</span></div></div><p>Um dia com várias atividades conta uma vez. Dias sem registro não confirmam descanso.</p><Origin items={items.filter(a=>a.date>=streak.start&&a.date<=streak.end)} onOpen={onOpen}/></section>;}
export default function PerformanceSummaryInsights({activities,today,goals,onConfigureGoal,onEditGoal,onOpen}:{activities:PerformanceActivity[];today:string;goals:PerformanceGoal[];onConfigureGoal:()=>void;onEditGoal:(g:PerformanceGoal)=>void;onOpen:(a:PerformanceActivity)=>void}){
 const [length,setLength]=useState<3|6|12>(3),info=performanceInsights(activities,today,length);
 return <div className={styles.stack}>
  <div className={styles.grid}><section className={styles.panel}><header><div><small>MÊS ATUAL PARCIAL</small><h2>Comparação mensal</h2></div></header><p>{info.month} até {date(today)} × {info.lastMonth} completo. Não é uma projeção.</p><Totals items={info.current} previous={info.previous}/><Origin items={[...info.current,...info.previous]} onOpen={onOpen}/></section><section className={styles.panel}><header><div><small>ÚLTIMOS 7 DIAS</small><h2>Atividade recente</h2></div></header><p>{date(info.start7)} a {date(today)} · {info.activeDays} dias com atividade · {info.daysWithoutRecord} dias sem registro</p><Totals items={info.week}/><Origin items={info.week} onOpen={onOpen}/></section></div>
  <section className={styles.panel}><header><div><small>MESES ENCERRADOS</small><h2>Comparação entre períodos</h2></div><label>Janela<select value={length} onChange={e=>setLength(Number(e.target.value) as 3|6|12)}>{([3,6,12] as const).map(n=><option key={n} value={n}>{n} meses × {n} anteriores</option>)}</select></label></header><p>{info.startA} a {info.endA} × {info.startB} a {info.endB}. Sem base anterior, não há porcentagem.</p><Totals items={info.periodA} previous={info.periodB}/><Origin items={[...info.periodA,...info.periodB]} onOpen={onOpen}/></section>
  <div className={styles.grid}><PerformanceStreak activities={activities} today={today} onOpen={onOpen}/><section className={styles.panel}><header><div><small>REGISTROS ATÉ HOJE</small><h2>Distribuição por modalidade</h2></div></header>{info.distribution.length?info.distribution.map(item=><div key={item.type} className={styles.sport}><strong>{labels[item.type]||item.type}</strong><span>{item.count} atividades</span><Origin items={item.records} onOpen={onOpen}/></div>):<p>Nenhuma atividade registrada.</p>}</section></div>
  <section className={styles.panel}><header><div><small>OPCIONAIS · CONFIGURAÇÃO EXISTENTE</small><h2>Metas de Performance</h2></div><button type="button" onClick={onConfigureGoal}>+ Configurar meta</button></header><p>Metas mensais ou anuais, gerais ou por modalidade. Nenhuma meta é ativada automaticamente.</p>{goals.length?goals.map(goal=>{const items=info.items.filter(a=>a.date.startsWith(goal.period==='MONTHLY'?`${goal.year}-${String(goal.month||1).padStart(2,'0')}`:String(goal.year))&&(!goal.activityType||a.type===goal.activityType)),sum=activityTotals(items),metric=goal.metric==='DISTANCE_KM'?'distance':goal.metric==='DURATION_MINUTES'?'minutes':goal.metric==='ELEVATION_METERS'?'elevation':'count',spec=metrics.find(m=>m[0]===metric)!;return <button type="button" className={styles.goal} key={goal.id} onClick={()=>onEditGoal(goal)}><strong>{goal.activityType?labels[goal.activityType]:'Todas as modalidades'} · {spec[1]}</strong><span>{fmt(sum[metric])} / {fmt(goal.target)} {spec[2]} · {goal.period==='MONTHLY'?`${String(goal.month).padStart(2,'0')}/`:''}{goal.year}</span><small>Editar configuração →</small></button>;}):<p>Sem metas configuradas. Ative somente se desejar.</p>}</section>
 </div>;
}
